fos_rest:
    param_fetcher_listener: true
    body_listener: true
    format_listener: 
        rules:
            - { path: ^/, priorities: [ html, json, xml ], fallback_format: ~, prefer_extension: false }
            
    body_converter:
        enabled: true
        validate: true

    routing_loader:
        default_format: json                            # All responses should be JSON formated
        include_format: false

    view:
        view_response_listener: 'force'
        formats:
            xml:  true
            json: true
        templating_formats:
            html: true
        force_redirects:
            json: true

#    body_listener:
#        array_normalizer: fos_rest.normalizer.camel_keys

    exception:
        codes:
            'Symfony\Component\Routing\Exception\ResourceNotFoundException': 404
            'Doctrine\ORM\OptimisticLockException': HTTP_CONFLICT
        messages:
            'Symfony\Component\Routing\Exception\ResourceNotFoundException': true
    allowed_methods_listener: true
    access_denied_listener:
        json: true

    disable_csrf_role: ROLE_API


nelmio_api_doc:
    name: API Documentation